### ISSUE TITLE
rwc fail

### ISSUE THREAD

**Issue by bmcfee** [ejhumphrey/minst-dataset#9]
`make download` worked okay.

`make build` is failing:

```
→  make build
python scripts/segment_audio.py rwc_index.csv rwc_notes.csv ~/data/segments/audio_files
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
2016-07-27 14:14:33,767 {segment_audio.py:segment_audio} [INFO] segment_audio(): Begin segment_audio()
Traceback (most recent call last):
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/pandas/indexes/base.py", line 1945, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'onsets_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/segment_audio.py", line 165, in <module>
    arguments['--pass_thru'])
  File "scripts/segment_audio.py", line 111, in segment_audio
    segment_df = segment_df[segment_df['onsets_file'].notnull()]
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/home/bmcfee/miniconda/envs/py35/lib/python3.5/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'onsets_file'
make: *** [rwc_notes.csv] Error 1
```

**Comment by bmcfee** [comment]
tagging @cjacoby

**Comment by cjacoby** [comment]
@bmcfee - I _think_ this is no longer an issue, but I'll try to have @ejhumphrey run it to see if thats true or not.__

**Comment by cjacoby** [comment]
Relatively confident this is no longer an issue.
@ejhumphrey - can you run a full `make build` with all the data on your machine and prove that it works sometime in the next couple of days? Should take about an hour to run.

**Comment by ejhumphrey** [comment]
confirmed, this is all set
